language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
env:
    - NODE_ENV=production
script:
  - npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: cso-interchange
    region: us-west-1
    skip_cleanup: true
    local-dir: build
    acl: public_read
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: cso-interchange-develop
    region: us-west-1
    skip_cleanup: true
    local-dir: build
    acl: public_read
    on:
      branch: develop
    provider: heroku
    on:
      branch: develop
    api_key:
      master:
        secure: f8e0acde-1839-41f2-9d12-0b2cfea7e33d
    app:
      master: dev-cio-ciso-interchange
    strategy: git
after_deploy:
  # Invalidate every object in the distribution.
  - bin/auto-invalidate.sh
