language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "$HOME/.cache/pip"
env:
    - NODE_ENV=production
script:
  - npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: cso-interchange
    region: us-west-1
    skip_cleanup: true
    local-dir: build
    acl: public_read
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: cso-interchange-develop
    region: us-west-1
    skip_cleanup: true
    local-dir: build
    acl: public_read
    on:
      branch: develop
after_deploy:
  # `awscli` is required for invalidation of CloudFront distributions.
  - pip install awscli
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the distribution.
  - aws cloudfront create-invalidation --distribution-id E3IMNPFARDQRBW --paths "/*"
  # Invalidate every object in the dev distribution.
  - aws cloudfront create-invalidation --distribution-id E2TVYMKZI6J13B --paths "/*"
